// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_505 from "./routes/_505.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Cta from "./islands/Cta.tsx";
import * as $FAQ from "./islands/FAQ.tsx";
import * as $Hero from "./islands/Hero.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $Team from "./islands/Team.tsx";
import * as $Testimonials from "./islands/Testimonials.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_505.tsx": $_505,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Cta.tsx": $Cta,
    "./islands/FAQ.tsx": $FAQ,
    "./islands/Hero.tsx": $Hero,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/Team.tsx": $Team,
    "./islands/Testimonials.tsx": $Testimonials,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
